POST http://localhost:3333/videos
Content-Type:application/json

{
    "title": "video node",
    "description": "video 010101" ,
    "duration":180
}

###

GET  http://localhost:3333/videos

###

PUT   http://localhost:3333/videos/adcf961d-9632-4c62-ae24-ba09d977eb2d
Content-Type:application/json

{
    "title": "video 0333",
    "description": "video 010101",
    "duration":180
}


###
DELETE    http://localhost:3333/videos/adcf961d-9632-4c62-ae24-ba09d977eb2d